#!/usr/bin/env python3
"""catalog-downloads.py — build the LIVE CATALOG of ~/Downloads (every file classified
and linked to estate status). Output: docs/catalog/LIVE-CATALOG-<date>.md

Classes:
  PLAN   — markdown plan/playbook/backlog (worked-into-repo or queued)
  ASSET  — images/logos/pptx/pdf marketing + evidence assets
  ARCH   — zip archives (sessions, playbooks, site bundles) — inventory only
  TOOL   — code (.py/.js/.mjs/.sh) scripts/harnesses
  DATA   — json/csv/sav data corpora
  DOC    — docx/pdf documents (briefings, agreements, proposals)
  OTHER  — everything else
"""
import os, sys, datetime, re

DOWNLOADS = os.path.expanduser("~/Downloads")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "catalog")

PLAN_KW = ["playbook","master","backlog","sprint","next-100","next 100","rundown","plan","steps","move",
           "alignment","strategy","blueprint","roadmap","execution","outstanding"]
ARCH_KW = ["zip"]
TOOL_KW = [".py",".mjs",".js",".sh",".ts"]
DATA_KW = [".json",".csv",".sav",".jsonl"]
DOC_KW = [".docx",".pdf",".doc",".pptx"]
ASSET_KW = [".png",".jpg",".jpeg",".svg",".webp",".avif",".gif"]

def classify(fn):
    ext = os.path.splitext(fn)[1].lower()
    low = fn.lower()
    if ext in TOOL_KW: return "TOOL"
    if ext in DATA_KW: return "DATA"
    if ext in DOC_KW: return "DOC"
    if ext in ASSET_KW: return "ASSET"
    if ext == ".zip": return "ARCH"
    if ext == ".md" or ext in (".mdx",".txt"):
        if any(k in low for k in PLAN_KW): return "PLAN"
        return "MD-NOTE"
    return "OTHER"

def main():
    files = sorted([f for f in os.listdir(DOWNLOADS) if not f.startswith(".")])
    rows = []
    for f in files:
        cls = classify(f)
        size = os.path.getsize(os.path.join(DOWNLOADS, f))
        mtime = datetime.date.fromtimestamp(os.path.getmtime(os.path.join(DOWNLOADS, f))).isoformat()
        rows.append((cls, mtime, size, f))
    date = datetime.date.today().isoformat()
    os.makedirs(OUT, exist_ok=True)
    out = [f"# LIVE CATALOG — ~/Downloads → estate · {date}", "",
           f"**{len(rows)} files.** Classification: PLAN=plans folded/queued in repo · ASSET=brand/evidence · "
           "ARCH=archive bundles · TOOL=code · DATA=corpora · DOC=documents · MD-NOTE=notes. "
           "Repo-of-record: github.com/CSOAI-ORG/cibola (docs/) + councilof-ai (live site).", ""]
    from collections import Counter
    cnt = Counter(r[0] for r in rows)
    out.append("## By class\n")
    for cls, n in cnt.most_common(): out.append(f"- {cls}: {n}")
    out.append("\n## PLAN docs (worked-through candidates — read newest first)\n")
    plans = [r for r in rows if r[0] == "PLAN"]
    for cls, mt, sz, f in sorted(plans, key=lambda r: r[1], reverse=True)[:60]:
        out.append(f"- `{f}` (mtime {mt})")
    out.append("\n## ARCH bundles (inventory)\n")
    for cls, mt, sz, f in sorted([r for r in rows if r[0] == "ARCH"], key=lambda r: r[1], reverse=True)[:40]:
        out.append(f"- `{f}` ({sz//1024} KB, {mt})")
    out.append("\n## TOOL / DATA (recent)\n")
    for cls, mt, sz, f in sorted([r for r in rows if r[0] in ("TOOL","DATA")], key=lambda r: r[1], reverse=True)[:40]:
        out.append(f"- `{f}` ({mt})")
    out.append("\n## DOC (recent)\n")
    for cls, mt, sz, f in sorted([r for r in rows if r[0] == "DOC"], key=lambda r: r[1], reverse=True)[:40]:
        out.append(f"- `{f}` ({mt})")
    out.append("\n_Generated by scripts/catalog-downloads.py — re-run anytime to refresh._")
    path = os.path.join(OUT, f"LIVE-CATALOG-{date}.md")
    open(path, "w").write("\n".join(out))
    print(f"catalog written: {path} ({len(rows)} files)")

if __name__ == "__main__":
    main()
